export const productData: Record<
  string,
  {
    title: string;
    tagline: string;
    heroDesc: string;
    image: string;
    color: string;
    story: string;
    process: string;
    ingredients: string;
    allergens: string;
    nutrition: { label: string; value: string }[];
    pairings: string[];
    storage: string;
    weight: string;
    origin: string;
  }
> = {
  "himalayan-salt": {
    title: "Himalayan Salt",
    tagline: "Pure Simplicity, Elevated",
    heroDesc: "The timeless elegance of pink Himalayan salt meets the ethereal crunch of hand-popped Makhana. A minimalist masterpiece for the discerning palate.",
    image: "/flavor_salt_v2.png",
    color: "#FDF6F0",
    story: "Sourced from the ancient Khewra salt mines at the foothills of the Himalayas, our pink salt carries over 84 trace minerals that have been preserved for 250 million years. When paired with the delicate, air-popped texture of Bihar's finest Makhana seeds, it creates a snack that is both profoundly simple and deeply satisfying. This is the flavor that started our journey — a tribute to the philosophy that the finest ingredients need nothing more than each other.",
    process: "Each Makhana seed is hand-harvested from the pristine ponds of Bihar, sun-dried for 48 hours, and then popped using traditional heat methods — no oil, no machines. The seeds are then lightly misted with cold-pressed extra virgin olive oil and dusted with finely ground Himalayan pink salt. The result is a snack with less than 2% fat content that delivers a satisfying crunch in every bite.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (92%), cold-pressed extra virgin olive oil (5%), Himalayan pink salt (3%).",
    allergens: "Naturally gluten-free. No nuts. No soy. No dairy. Produced in a facility that handles tree nuts and sesame.",
    nutrition: [
      { label: "Energy", value: "110 kcal" },
      { label: "Protein", value: "3.0 g" },
      { label: "Total Fat", value: "1.8 g" },
      { label: "Carbohydrates", value: "21 g" },
      { label: "Dietary Fiber", value: "1.4 g" },
      { label: "Sodium", value: "180 mg" },
      { label: "Calcium", value: "25 mg" },
      { label: "Iron", value: "0.8 mg" },
    ],
    pairings: [
      "Pairs beautifully with a crisp Chablis or Sauvignon Blanc",
      "Excellent alongside hummus or tzatziki",
      "A refined addition to any cheese board",
      "Perfect with sparkling water and a slice of lemon",
    ],
    storage: "Store in a cool, dry place away from direct sunlight. Once opened, reseal tightly and consume within 7 days for optimal crunch.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Salt: Khewra, Pakistan · Olive Oil: Andalusia, Spain",
  },
  "herbes-de-provence": {
    title: "Herbes de Provence",
    tagline: "Le Jardin Méditerranéen",
    heroDesc: "Thym, romarin, sarriette, origan et basilic — l'âme aromatique du Sud de la France capturée dans chaque graine de Makhana soufflée à l'air.",
    image: "/flavor_herbes_v2.png",
    color: "#F5F7F0",
    story: "Le mélange d'herbes de Provence est une lettre d'amour aux collines ensoleillées du Sud de la France, où les herbes sauvages poussent en abondance parmi les champs de lavande. Notre mélange exclusif utilise uniquement des herbes entières séchées, soigneusement sélectionnées dans des fermes biologiques certifiées de la vallée du Luberon. Chaque herbe est récoltée à pleine maturité et séchée délicatement pour préserver ses huiles essentielles. Associées à la toile neutre et aérée du Makhana, les herbes chantent — offrant une expérience aromatique qui vous transporte dans un jardin provençal à chaque poignée.",
    process: "Les graines de Makhana subissent notre processus exclusif de soufflage à zéro huile, puis reçoivent un léger enrobage d'huile d'olive extra vierge premium issue d'oliviers centenaires d'Andalousie. Les herbes de Provence sont ensuite précisément dosées et mélangées avec les graines en petits lots pour assurer une distribution uniforme. Chaque lot est dégusté par notre équipe qualité avant conditionnement.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (88%), huile d'olive extra vierge (5%), mélange d'herbes de Provence (thym, romarin, sarriette, origan, basilic) (5%), sel de mer (2%).",
    allergens: "Naturellement sans gluten. Sans noix. Sans soja. Sans produits laitiers. Fabriqué dans un établissement qui traite des noix et du sésame.",
    nutrition: [
      { label: "Énergie", value: "115 kcal" },
      { label: "Protéines", value: "3,2 g" },
      { label: "Lipides Totaux", value: "2,1 g" },
      { label: "Glucides", value: "21 g" },
      { label: "Fibres Alimentaires", value: "1,6 g" },
      { label: "Sodium", value: "150 mg" },
      { label: "Calcium", value: "28 mg" },
      { label: "Fer", value: "1,0 mg" },
    ],
    pairings: [
      "Idéal avec un rosé frais de Provence",
      "Complète parfaitement le chèvre et la tapenade d'olives",
      "Une alternative gastronomique aux croûtons dans les salades",
      "À servir avec des légumes grillés et des sauces",
    ],
    storage: "Conserver dans un endroit frais et sec, à l'abri de la lumière directe du soleil. Une fois ouvert, refermer hermétiquement et consommer dans les 7 jours pour un craquant optimal.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Herbes : Luberon, France · Huile d'Olive : Andalousie, Espagne",
  },
  "black-truffle": {
    title: "Black Truffle",
    tagline: "The Black Gold of Apéro",
    heroDesc: "The intoxicating aroma of Périgord black truffle, elevated by the cloud-like lightness of Makhana. Accessible luxury, redefined.",
    image: "/flavor_truffle_v2.png",
    color: "#F5F3F0",
    story: "The Périgord black truffle (Tuber Melanosporum) has been the crown jewel of French gastronomy for centuries. Prized by chefs worldwide for its deep, earthy, and slightly musky aroma, it transforms any dish it touches into something extraordinary. We worked with truffle artisans from the Dordogne region to develop a proprietary seasoning that captures the essence of freshly shaved truffle. Combined with the ethereal crunch of hand-popped Makhana and a whisper of Guérande sea salt, this is our most indulgent creation — proof that luxury and health can coexist beautifully.",
    process: "Our truffle seasoning is crafted from real summer black truffle pieces (Tuber Aestivum) combined with natural truffle aroma derived from the prestigious Périgord variety. The Makhana seeds are first lightly coated with extra virgin olive oil, then the truffle blend is carefully applied in our temperature-controlled facility to preserve the volatile aromatic compounds. Finally, a delicate finish of hand-harvested Guérande sea salt adds mineral complexity.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (86%), extra virgin olive oil (6%), summer black truffle pieces (Tuber Aestivum) (3%), natural truffle aroma (2%), Guérande sea salt (3%).",
    allergens: "Naturally gluten-free. No nuts. No soy. No dairy. Contains truffle. Produced in a facility that handles tree nuts and sesame.",
    nutrition: [
      { label: "Energy", value: "118 kcal" },
      { label: "Protein", value: "3.5 g" },
      { label: "Total Fat", value: "2.5 g" },
      { label: "Carbohydrates", value: "20.5 g" },
      { label: "Dietary Fiber", value: "1.5 g" },
      { label: "Sodium", value: "160 mg" },
      { label: "Calcium", value: "22 mg" },
      { label: "Iron", value: "0.9 mg" },
    ],
    pairings: [
      "Exceptional with a glass of aged Burgundy or Barolo",
      "Sublime alongside aged Comté or Parmigiano-Reggiano",
      "Elevates any charcuterie board to gastronomic heights",
      "Perfect with champagne for celebrations",
    ],
    storage: "Store in a cool, dry place away from direct sunlight. Once opened, reseal tightly and consume within 5 days to preserve truffle aroma.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Truffle: Dordogne, France · Salt: Guérande, France",
  },
  "mediterranean-herb-fusion": {
    title: "Mediterranean Herb Fusion",
    tagline: "The Mediterranean Garden",
    heroDesc: "Thyme, rosemary, savory, oregano, and basil — the aromatic soul of the South of France captured in each air-popped Makhana seed.",
    image: "/flavor_herbes_v2.png",
    color: "#F5F7F0",
    story: "The Herbes de Provence blend is a love letter to the sun-drenched hills of the South of France, where wild herbs grow in abundance among lavender fields. Our exclusive blend uses only whole dried herbs, carefully selected from certified organic farms in the Luberon valley. Each herb is harvested at full maturity and delicately dried to preserve its essential oils. Paired with the neutral and airy canvas of Makhana, the herbs sing — offering an aromatic experience that transports you to a Provençal garden with every handful.",
    process: "The Makhana seeds undergo our proprietary zero-oil popping process, then receive a light coating of premium extra virgin olive oil from century-old olive trees in Andalusia. The Herbes de Provence are then precisely measured and blended with the seeds in small batches to ensure uniform distribution. Each batch is tasted by our quality team before packaging.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (88%), extra virgin olive oil (5%), Herbes de Provence blend (thyme, rosemary, savory, oregano, basil) (5%), sea salt (2%).",
    allergens: "Naturally gluten-free. No nuts. No soy. No dairy. Produced in a facility that handles tree nuts and sesame.",
    nutrition: [
      { label: "Energy", value: "115 kcal" },
      { label: "Protein", value: "3.2 g" },
      { label: "Total Fat", value: "2.1 g" },
      { label: "Carbohydrates", value: "21 g" },
      { label: "Dietary Fiber", value: "1.6 g" },
      { label: "Sodium", value: "150 mg" },
      { label: "Calcium", value: "28 mg" },
      { label: "Iron", value: "1.0 mg" },
    ],
    pairings: [
      "Ideal with a crisp rosé from Provence",
      "Perfectly complements goat cheese and olive tapenade",
      "A gourmet alternative to croutons in salads",
      "Serve alongside grilled vegetables and dips",
    ],
    storage: "Store in a cool, dry place away from direct sunlight. Once opened, reseal tightly and consume within 7 days for optimal crunch.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Herbs: Luberon, France · Olive Oil: Andalusia, Spain",
  },
  "caramel-salt": {
    title: "Caramel & Salt",
    tagline: "Sweet & Salty Indulgence",
    heroDesc: "A luxurious blend of rich caramel and a hint of sea salt, perfectly balanced on our air-popped Makhana.",
    image: "/flavor_caramel_salt.png",
    color: "#F9ECD9",
    story: "Crafted for those who crave the perfect balance of sweet and savory. Our Caramel & Salt Makhana takes inspiration from classic French confectionery. We use traditional caramel-making techniques, carefully melting unrefined sugar and blending it with a touch of premium sea salt. The result is a delicate, crunchy glaze over our airy Makhana seeds that delivers a sophisticated dessert-like experience without the heavy guilt.",
    process: "The Makhana seeds are popped without oil, then carefully tumbled in small batches with our handcrafted caramel glaze. We finish each batch with a precise dusting of sea salt before it cools, ensuring a perfect sweet-salty crunch in every bite.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (70%), unrefined cane sugar (20%), cold-pressed sunflower oil (8%), sea salt (2%).",
    allergens: "Naturally gluten-free. No soy. Produced in a facility that handles tree nuts and sesame. May contain traces of dairy.",
    nutrition: [
      { label: "Energy", value: "145 kcal" },
      { label: "Protein", value: "2.5 g" },
      { label: "Total Fat", value: "3.0 g" },
      { label: "Carbohydrates", value: "28 g" },
      { label: "Dietary Fiber", value: "1.2 g" },
      { label: "Sodium", value: "180 mg" },
      { label: "Calcium", value: "20 mg" },
      { label: "Iron", value: "0.8 mg" },
    ],
    pairings: [
      "Perfect with a rich espresso or flat white",
      "A delightful topping for vanilla bean ice cream",
      "Enjoy as a sophisticated mid-afternoon treat",
    ],
    storage: "Store in a cool, dry place away from direct sunlight. Once opened, reseal tightly and consume within 5 days to maintain the crisp caramel shell.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Caramel & Salt: Crafted in France",
  },
  "dark-chocolate": {
    title: "Dark Chocolate",
    tagline: "Decadent & Intense",
    heroDesc: "Rich, 70% single-origin dark chocolate gently coating our premium puffed Makhana for a deeply satisfying, guilt-free indulgence.",
    image: "/flavor_dark_chocolate.png",
    color: "#EFEAE6",
    story: "For the true chocolate aficionado. We partnered with master chocolatiers to source a 70% single-origin cocoa that perfectly complements the earthy, roasted notes of our Makhana. This is not a candy; it is a refined snacking experience where the bitter-sweet complexity of premium dark chocolate meets an irresistible airy crunch.",
    process: "Each roasted Makhana seed is delicately enrobed in tempered dark chocolate. Our panning process ensures a thin, even layer of chocolate that snaps perfectly when bitten, melting smoothly to reveal the crisp seed inside.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (60%), 70% dark chocolate (cocoa mass, cane sugar, cocoa butter, vanilla extract) (40%).",
    allergens: "Naturally gluten-free. No soy. Produced in a facility that handles tree nuts, dairy, and sesame.",
    nutrition: [
      { label: "Energy", value: "155 kcal" },
      { label: "Protein", value: "3.5 g" },
      { label: "Total Fat", value: "6.5 g" },
      { label: "Carbohydrates", value: "22 g" },
      { label: "Dietary Fiber", value: "3.0 g" },
      { label: "Sodium", value: "10 mg" },
      { label: "Calcium", value: "30 mg" },
      { label: "Iron", value: "1.5 mg" },
    ],
    pairings: [
      "Stunning alongside a robust Cabernet Sauvignon",
      "Pairs beautifully with aged rum or cognac",
      "A luxurious companion to Earl Grey tea",
    ],
    storage: "Store in a cool, dry place between 15°C and 18°C. Do not refrigerate. Once opened, consume within 7 days.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Chocolate: Sourced from Ecuador",
  },
  "lemon-mint": {
    title: "Lemon & Mint",
    tagline: "Zesty & Refreshing",
    heroDesc: "A bright, citrusy burst of lemon paired with cooling mint. The ultimate palate-cleansing summer snack.",
    image: "/flavor_lemon_mint.png",
    color: "#F4FAEB",
    story: "Inspired by the refreshing lemonades of Mediterranean summers, this flavor profile is designed to awaken the senses. The sharp, vibrant zest of natural lemon oil is beautifully counterbalanced by the cooling finish of dried spearmint. It is a bold, unexpected take on savory snacking that leaves you feeling energized.",
    process: "After our zero-oil roasting, the Makhana is lightly misted with extra virgin olive oil infused with cold-pressed lemon rind extract and dusted with finely milled organic mint leaves.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (88%), extra virgin olive oil (6%), natural lemon extract (3%), dried mint (2%), sea salt (1%).",
    allergens: "Naturally gluten-free. No nuts. No soy. No dairy. Produced in a facility that handles tree nuts and sesame.",
    nutrition: [
      { label: "Energy", value: "110 kcal" },
      { label: "Protein", value: "3.0 g" },
      { label: "Total Fat", value: "1.8 g" },
      { label: "Carbohydrates", value: "20 g" },
      { label: "Dietary Fiber", value: "1.5 g" },
      { label: "Sodium", value: "120 mg" },
      { label: "Calcium", value: "25 mg" },
      { label: "Iron", value: "0.9 mg" },
    ],
    pairings: [
      "Perfectly accompanies a chilled gin and tonic",
      "Refreshing alongside a crisp iced tea",
      "A great contrast to spicy dishes",
    ],
    storage: "Store in a cool, dry place. Reseal tightly after opening.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Lemon & Mint: Mediterranean Basin",
  },
  "peanut-butter": {
    title: "Peanut Butter",
    tagline: "Creamy Protein Power",
    heroDesc: "Smooth, roasted peanut butter naturally coats our Makhana for a protein-packed, melt-in-the-mouth experience.",
    image: "/flavor_peanut_butter.png",
    color: "#F6EEDF",
    story: "We wanted to create the ultimate fitness-friendly snack without compromising on gourmet appeal. By using 100% natural, freshly roasted peanuts milled into a smooth paste, we developed a coating that is both intensely flavorful and nutritionally dense. It is the perfect marriage of complex carbohydrates and healthy plant-based proteins.",
    process: "The Makhana seeds are gently tumbled with warm, pure peanut butter and a touch of sea salt, creating a delicate, creamy layer that dries to a perfect matte finish without being sticky.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (75%), roasted peanuts (22%), sea salt (3%).",
    allergens: "Contains peanuts. Naturally gluten-free. No soy. No dairy. Produced in a facility that handles other tree nuts and sesame.",
    nutrition: [
      { label: "Energy", value: "160 kcal" },
      { label: "Protein", value: "6.5 g" },
      { label: "Total Fat", value: "7.0 g" },
      { label: "Carbohydrates", value: "18 g" },
      { label: "Dietary Fiber", value: "2.5 g" },
      { label: "Sodium", value: "150 mg" },
      { label: "Calcium", value: "30 mg" },
      { label: "Iron", value: "1.2 mg" },
    ],
    pairings: [
      "The ideal post-workout recovery snack",
      "Delicious with a sliced apple or banana",
      "Pairs nicely with a stout or porter beer",
    ],
    storage: "Store in a cool, dry place. Avoid heat to prevent the peanut coating from softening.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Peanuts: Saurashtra, India",
  },
  "peri-peri": {
    title: "Peri Peri",
    tagline: "Fiery African Heat",
    heroDesc: "A bold, vibrant blend of African bird's eye chili, citrus, and garlic. For those who crave an elegant, fiery kick.",
    image: "/flavor_peri_peri.png",
    color: "#FFF0ED",
    story: "Paying homage to the iconic African-Portuguese flavor profile, our Peri Peri Makhana is an adventurous explosion of taste. We spent months perfecting the spice blend to ensure the heat builds slowly, allowing the complex notes of garlic, lemon, and smoked paprika to shine before the bird's eye chili leaves a lingering, pleasant warmth.",
    process: "Our custom Peri Peri spice blend is dry-roasted to release its essential oils, then dusted over olive oil-misted Makhana in a specialized tumbling drum for perfectly even coverage.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (85%), extra virgin olive oil (7%), Peri Peri spice blend (chili, garlic, lemon powder, paprika, onion) (6%), sea salt (2%).",
    allergens: "Naturally gluten-free. No nuts. No soy. No dairy. Produced in a facility that handles tree nuts and sesame.",
    nutrition: [
      { label: "Energy", value: "115 kcal" },
      { label: "Protein", value: "3.2 g" },
      { label: "Total Fat", value: "2.5 g" },
      { label: "Carbohydrates", value: "20 g" },
      { label: "Dietary Fiber", value: "1.8 g" },
      { label: "Sodium", value: "190 mg" },
      { label: "Calcium", value: "26 mg" },
      { label: "Iron", value: "1.1 mg" },
    ],
    pairings: [
      "Incredible with an ice-cold lager or IPA",
      "A spicy companion to tropical fruit juices",
      "Elevates a simple avocado toast",
    ],
    storage: "Store in a cool, dry place away from direct sunlight.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Spices: Global Sourcing",
  },
  "smokey-bbq": {
    title: "Smokey BBQ",
    tagline: "Wood-Fired Perfection",
    heroDesc: "Deep, smoky hickory notes paired with a touch of molasses sweetness and savory spices. A classic reinvented.",
    image: "/flavor_smokey_bbq.png",
    color: "#F4EBE3",
    story: "We set out to create a BBQ flavor that feels authentic and grown-up. Instead of artificial smoke flavors, we use naturally smoked paprika and a carefully curated blend of spices to evoke the sensation of a slow, wood-fired barbecue. It is robust, slightly sweet, and deeply satisfying, offering all the comfort of a classic BBQ snack without the heavy processing.",
    process: "The Makhana seeds are coated with our proprietary BBQ rub, featuring naturally smoked Spanish paprika, before being lightly baked to lock in the deep, smoky aroma.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (85%), cold-pressed sunflower oil (6%), BBQ spice blend (smoked paprika, tomato powder, onion, garlic, unrefined sugar) (7%), sea salt (2%).",
    allergens: "Naturally gluten-free. No nuts. No soy. No dairy. Produced in a facility that handles tree nuts and sesame.",
    nutrition: [
      { label: "Energy", value: "120 kcal" },
      { label: "Protein", value: "3.1 g" },
      { label: "Total Fat", value: "2.2 g" },
      { label: "Carbohydrates", value: "21 g" },
      { label: "Dietary Fiber", value: "1.7 g" },
      { label: "Sodium", value: "170 mg" },
      { label: "Calcium", value: "28 mg" },
      { label: "Iron", value: "1.0 mg" },
    ],
    pairings: [
      "Pairs brilliantly with an amber ale or bourbon",
      "A great crunchy addition to a hearty chili",
      "Perfect for outdoor picnics and gatherings",
    ],
    storage: "Store in a cool, dry place. Reseal tightly after opening.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Smoked Paprika: Spain",
  },
  "tangy-tomato": {
    title: "Tangy Tomato",
    tagline: "Sun-Ripened Zest",
    heroDesc: "The sweet and tart brilliance of sun-ripened tomatoes, seasoned with subtle herbs for a vibrant, savory crunch.",
    image: "/flavor_tangy_tomato.png",
    color: "#FEF0F0",
    story: "Capturing the essence of a late-summer harvest. Our Tangy Tomato Makhana uses real, spray-dried tomato powder to deliver an authentic, concentrated burst of umami and acidity. It is a nostalgic flavor profile elevated by the purity of our ingredients—no artificial colorants, just the natural vibrancy of vine-ripened tomatoes.",
    process: "Premium tomato powder is blended with a touch of oregano and sea salt, then delicately dusted over freshly popped, olive oil-misted Makhana seeds to ensure maximum flavor adherence.",
    ingredients: "Popped Euryale Ferox seeds (Makhana) (86%), extra virgin olive oil (5%), tomato powder (6%), mixed herbs (1%), sea salt (2%).",
    allergens: "Naturally gluten-free. No nuts. No soy. No dairy. Produced in a facility that handles tree nuts and sesame.",
    nutrition: [
      { label: "Energy", value: "115 kcal" },
      { label: "Protein", value: "3.3 g" },
      { label: "Total Fat", value: "1.9 g" },
      { label: "Carbohydrates", value: "21.5 g" },
      { label: "Dietary Fiber", value: "1.9 g" },
      { label: "Sodium", value: "160 mg" },
      { label: "Calcium", value: "24 mg" },
      { label: "Iron", value: "1.2 mg" },
    ],
    pairings: [
      "Excellent with a light Pilsner or pale ale",
      "A delightful alternative to croutons in gazpacho",
      "Kids love it as a healthy lunchbox addition",
    ],
    storage: "Store in a cool, dry place. The natural tomato powder is sensitive to moisture; reseal immediately after use.",
    weight: "Pack Size: 30g",
    origin: "Makhana: Bihar, India · Tomatoes: Italy",
  },
  "caramel-beurre-sale": {
    title: "Caramel & Beurre Salé",
    tagline: "Indulgence Sucrée-Salée",
    heroDesc: "Un mélange luxueux de caramel riche et d'une pointe de sel de mer, parfaitement équilibré sur notre Makhana soufflé.",
    image: "/flavor_caramel_salt.png",
    color: "#F9ECD9",
    story: "Créé pour ceux qui recherchent l'équilibre parfait entre le sucré et le salé. Notre Makhana Caramel & Beurre Salé s'inspire de la confiserie française classique. Nous utilisons des techniques traditionnelles de fabrication du caramel, en faisant fondre avec soin du sucre non raffiné et en y ajoutant une touche de sel marin premium. Le résultat est un glaçage délicat et croquant sur nos graines de Makhana aérées qui offre une expérience sophistiquée de dessert, sans la culpabilité.",
    process: "Les graines de Makhana sont soufflées sans huile, puis soigneusement mélangées en petits lots avec notre glaçage au caramel artisanal. Nous terminons chaque lot par un saupoudrage précis de sel marin avant qu'il ne refroidisse, garantissant un croquant sucré-salé parfait à chaque bouchée.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (70%), sucre de canne non raffiné (20%), huile de tournesol pressée à froid (8%), sel de mer (2%).",
    allergens: "Naturellement sans gluten. Sans soja. Fabriqué dans un établissement qui traite des noix et du sésame. Peut contenir des traces de produits laitiers.",
    nutrition: [
      { label: "Énergie", value: "145 kcal" },
      { label: "Protéines", value: "2,5 g" },
      { label: "Lipides Totaux", value: "3,0 g" },
      { label: "Glucides", value: "28 g" },
      { label: "Fibres Alimentaires", value: "1,2 g" },
      { label: "Sodium", value: "180 mg" },
      { label: "Calcium", value: "20 mg" },
      { label: "Fer", value: "0,8 mg" },
    ],
    pairings: [
      "Parfait avec un expresso riche ou un flat white",
      "Une garniture délicieuse pour une glace à la vanille",
      "À déguster comme une gâterie sophistiquée en milieu d'après-midi",
    ],
    storage: "Conserver dans un endroit frais et sec, à l'abri de la lumière directe du soleil. Une fois ouvert, refermer hermétiquement et consommer dans les 5 jours pour conserver la coquille de caramel croquante.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Caramel & Sel : Fabriqué en France",
  },
  "chocolat-noir": {
    title: "Chocolat Noir",
    tagline: "Décadent & Intense",
    heroDesc: "Un riche chocolat noir 70% d'origine unique enrobant délicatement notre Makhana soufflé premium pour une indulgence profondément satisfaisante.",
    image: "/flavor_dark_chocolate.png",
    color: "#EFEAE6",
    story: "Pour le véritable aficionado du chocolat. Nous nous sommes associés à des maîtres chocolatiers pour trouver un cacao d'origine unique à 70% qui complète parfaitement les notes terreuses et torréfiées de notre Makhana. Ce n'est pas un bonbon ; c'est une expérience de grignotage raffinée où la complexité douce-amère du chocolat noir premium rencontre un croquant aéré irrésistible.",
    process: "Chaque graine de Makhana torréfiée est délicatement enrobée de chocolat noir tempéré. Notre processus de dragéification assure une fine couche uniforme de chocolat qui se brise parfaitement à la morsure, fondant doucement pour révéler la graine croustillante à l'intérieur.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (60%), chocolat noir 70% (pâte de cacao, sucre de canne, beurre de cacao, extrait de vanille) (40%).",
    allergens: "Naturellement sans gluten. Sans soja. Fabriqué dans un établissement qui traite des noix, des produits laitiers et du sésame.",
    nutrition: [
      { label: "Énergie", value: "155 kcal" },
      { label: "Protéines", value: "3,5 g" },
      { label: "Lipides Totaux", value: "6,5 g" },
      { label: "Glucides", value: "22 g" },
      { label: "Fibres Alimentaires", value: "3,0 g" },
      { label: "Sodium", value: "10 mg" },
      { label: "Calcium", value: "30 mg" },
      { label: "Fer", value: "1,5 mg" },
    ],
    pairings: [
      "Époustouflant aux côtés d'un robuste Cabernet Sauvignon",
      "Se marie à merveille avec un rhum vieilli ou un cognac",
      "Un compagnon luxueux pour le thé Earl Grey",
    ],
    storage: "Conserver dans un endroit frais et sec entre 15°C et 18°C. Ne pas réfrigérer. Une fois ouvert, consommer dans les 7 jours.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Chocolat : Origine Équateur",
  },
  "citron-menthe": {
    title: "Citron & Menthe",
    tagline: "Piquant & Rafraîchissant",
    heroDesc: "Un éclat vif et citronné de citron associé à la fraîcheur de la menthe. Le snack estival ultime pour nettoyer le palais.",
    image: "/flavor_lemon_mint.png",
    color: "#F4FAEB",
    story: "Inspiré des limonades rafraîchissantes des étés méditerranéens, ce profil de saveur est conçu pour éveiller les sens. Le zeste vif et vibrant de l'huile de citron naturelle est magnifiquement contrebalancé par la finale rafraîchissante de la menthe verte séchée. C'est une interprétation audacieuse et inattendue du grignotage salé qui vous laisse plein d'énergie.",
    process: "Après notre torréfaction sans huile, le Makhana est légèrement vaporisé d'huile d'olive extra vierge infusée d'extrait d'écorce de citron pressée à froid et saupoudré de feuilles de menthe bio finement moulues.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (88%), huile d'olive extra vierge (6%), extrait naturel de citron (3%), menthe séchée (2%), sel de mer (1%).",
    allergens: "Naturellement sans gluten. Sans noix. Sans soja. Sans produits laitiers. Fabriqué dans un établissement qui traite des noix et du sésame.",
    nutrition: [
      { label: "Énergie", value: "110 kcal" },
      { label: "Protéines", value: "3,0 g" },
      { label: "Lipides Totaux", value: "1,8 g" },
      { label: "Glucides", value: "20 g" },
      { label: "Fibres Alimentaires", value: "1,5 g" },
      { label: "Sodium", value: "120 mg" },
      { label: "Calcium", value: "25 mg" },
      { label: "Fer", value: "0,9 mg" },
    ],
    pairings: [
      "Accompagne parfaitement un gin tonic bien frais",
      "Rafraîchissant aux côtés d'un thé glacé",
      "Un excellent contraste avec les plats épicés",
    ],
    storage: "Conserver dans un endroit frais et sec. Refermer hermétiquement après ouverture.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Citron & Menthe : Bassin Méditerranéen",
  },
  "beurre-de-cacahuete": {
    title: "Beurre de Cacahuète",
    tagline: "Puissance Protéinée Crémeuse",
    heroDesc: "Un beurre de cacahuète onctueux et torréfié enrobe naturellement notre Makhana pour une expérience fondante et riche en protéines.",
    image: "/flavor_peanut_butter.png",
    color: "#F6EEDF",
    story: "Nous voulions créer le snack fitness ultime sans compromettre l'attrait gourmand. En utilisant des cacahuètes 100% naturelles, fraîchement torréfiées et moulues en une pâte lisse, nous avons développé un enrobage à la fois intensément savoureux et dense sur le plan nutritionnel. C'est le mariage parfait entre des glucides complexes et des protéines végétales saines.",
    process: "Les graines de Makhana sont doucement mélangées avec du beurre de cacahuète pur et chaud et une touche de sel de mer, créant une couche délicate et crémeuse qui sèche pour un fini mat parfait sans être collante.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (75%), cacahuètes torréfiées (22%), sel de mer (3%).",
    allergens: "Contient des cacahuètes. Naturellement sans gluten. Sans soja. Sans produits laitiers. Fabriqué dans un établissement qui traite d'autres noix et du sésame.",
    nutrition: [
      { label: "Énergie", value: "160 kcal" },
      { label: "Protéines", value: "6,5 g" },
      { label: "Lipides Totaux", value: "7,0 g" },
      { label: "Glucides", value: "18 g" },
      { label: "Fibres Alimentaires", value: "2,5 g" },
      { label: "Sodium", value: "150 mg" },
      { label: "Calcium", value: "30 mg" },
      { label: "Fer", value: "1,2 mg" },
    ],
    pairings: [
      "Le snack de récupération post-entraînement idéal",
      "Délicieux avec une pomme ou une banane en tranches",
      "Se marie bien avec une bière stout ou porter",
    ],
    storage: "Conserver dans un endroit frais et sec. Éviter la chaleur pour empêcher l'enrobage de cacahuète de ramollir.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Cacahuètes : Saurashtra, Inde",
  },
  "peri-peri-fr": {
    title: "Peri Peri",
    tagline: "Chaleur Africaine Ardente",
    heroDesc: "Un mélange audacieux et vibrant de piment œil d'oiseau africain, d'agrumes et d'ail. Pour ceux qui recherchent un piquant élégant et ardent.",
    image: "/flavor_peri_peri.png",
    color: "#FFF0ED",
    story: "Rendant hommage au profil de saveur emblématique africo-portugais, notre Makhana Peri Peri est une explosion de goût aventureuse. Nous avons passé des mois à perfectionner le mélange d'épices pour garantir que la chaleur monte lentement, permettant aux notes complexes d'ail, de citron et de paprika fumé de briller avant que le piment œil d'oiseau ne laisse une chaleur agréable et persistante.",
    process: "Notre mélange d'épices Peri Peri sur mesure est torréfié à sec pour libérer ses huiles essentielles, puis saupoudré sur le Makhana vaporisé d'huile d'olive dans un tambour spécialisé pour une couverture parfaitement uniforme.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (85%), huile d'olive extra vierge (7%), mélange d'épices Peri Peri (piment, ail, poudre de citron, paprika, oignon) (6%), sel de mer (2%).",
    allergens: "Naturellement sans gluten. Sans noix. Sans soja. Sans produits laitiers. Fabriqué dans un établissement qui traite des noix et du sésame.",
    nutrition: [
      { label: "Énergie", value: "115 kcal" },
      { label: "Protéines", value: "3,2 g" },
      { label: "Lipides Totaux", value: "2,5 g" },
      { label: "Glucides", value: "20 g" },
      { label: "Fibres Alimentaires", value: "1,8 g" },
      { label: "Sodium", value: "190 mg" },
      { label: "Calcium", value: "26 mg" },
      { label: "Fer", value: "1,1 mg" },
    ],
    pairings: [
      "Incroyable avec une bière blonde ou une IPA glacée",
      "Un compagnon épicé pour les jus de fruits tropicaux",
      "Élève un simple toast à l'avocat",
    ],
    storage: "Conserver dans un endroit frais et sec, à l'abri de la lumière directe du soleil.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Épices : Approvisionnement Mondial",
  },
  "bbq-fume": {
    title: "BBQ Fumé",
    tagline: "Perfection au Feu de Bois",
    heroDesc: "Des notes profondes et fumées de caryer associées à une touche de douceur de mélasse et des épices savoureuses. Un classique réinventé.",
    image: "/flavor_smokey_bbq.png",
    color: "#F4EBE3",
    story: "Nous avons entrepris de créer une saveur BBQ authentique et mature. Au lieu de saveurs de fumée artificielles, nous utilisons du paprika espagnol naturellement fumé et un mélange d'épices soigneusement sélectionné pour évoquer la sensation d'un barbecue lent au feu de bois. C'est robuste, légèrement sucré et profondément satisfaisant, offrant tout le confort d'un snack BBQ classique sans la transformation lourde.",
    process: "Les graines de Makhana sont enrobées de notre mélange BBQ exclusif, contenant du paprika espagnol naturellement fumé, avant d'être légèrement cuites pour emprisonner l'arôme profond et fumé.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (85%), huile de tournesol pressée à froid (6%), mélange d'épices BBQ (paprika fumé, poudre de tomate, oignon, ail, sucre non raffiné) (7%), sel de mer (2%).",
    allergens: "Naturellement sans gluten. Sans noix. Sans soja. Sans produits laitiers. Fabriqué dans un établissement qui traite des noix et du sésame.",
    nutrition: [
      { label: "Énergie", value: "120 kcal" },
      { label: "Protéines", value: "3,1 g" },
      { label: "Lipides Totaux", value: "2,2 g" },
      { label: "Glucides", value: "21 g" },
      { label: "Fibres Alimentaires", value: "1,7 g" },
      { label: "Sodium", value: "170 mg" },
      { label: "Calcium", value: "28 mg" },
      { label: "Fer", value: "1,0 mg" },
    ],
    pairings: [
      "Se marie brillamment avec une bière ambrée ou un bourbon",
      "Un excellent ajout croquant à un piment copieux",
      "Parfait pour les pique-niques et les rassemblements en plein air",
    ],
    storage: "Conserver dans un endroit frais et sec. Refermer hermétiquement après ouverture.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Paprika Fumé : Espagne",
  },
  "tomate-acidulee": {
    title: "Tomate Acidulée",
    tagline: "Zeste Mûri au Soleil",
    heroDesc: "L'éclat sucré et acidulé des tomates mûries au soleil, assaisonné d'herbes subtiles pour un croquant vibrant et savoureux.",
    image: "/flavor_tangy_tomato.png",
    color: "#FEF0F0",
    story: "Capturer l'essence d'une récolte de fin d'été. Notre Makhana Tomate Acidulée utilise de la vraie poudre de tomate séchée par pulvérisation pour offrir une explosion authentique et concentrée d'umami et d'acidité. C'est un profil de saveur nostalgique rehaussé par la pureté de nos ingrédients — aucun colorant artificiel, juste l'éclat naturel des tomates mûries sur pied.",
    process: "La poudre de tomate premium est mélangée avec une touche d'origan et de sel de mer, puis délicatement saupoudrée sur des graines de Makhana fraîchement soufflées et vaporisées d'huile d'olive pour assurer une adhérence maximale de la saveur.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (86%), huile d'olive extra vierge (5%), poudre de tomate (6%), herbes variées (1%), sel de mer (2%).",
    allergens: "Naturellement sans gluten. Sans noix. Sans soja. Sans produits laitiers. Fabriqué dans un établissement qui traite des noix et du sésame.",
    nutrition: [
      { label: "Énergie", value: "115 kcal" },
      { label: "Protéines", value: "3,3 g" },
      { label: "Lipides Totaux", value: "1,9 g" },
      { label: "Glucides", value: "21,5 g" },
      { label: "Fibres Alimentaires", value: "1,9 g" },
      { label: "Sodium", value: "160 mg" },
      { label: "Calcium", value: "24 mg" },
      { label: "Fer", value: "1,2 mg" },
    ],
    pairings: [
      "Excellent avec une Pilsner légère ou une pale ale",
      "Une délicieuse alternative aux croûtons dans le gaspacho",
      "Les enfants l'adorent comme un ajout sain à la boîte à lunch",
    ],
    storage: "Conserver dans un endroit frais et sec. La poudre de tomate naturelle est sensible à l'humidité ; refermer immédiatement après utilisation.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Tomates : Italie",
  },
  "coming-soon": {
    title: "Coming Soon",
    tagline: "The Next Chapter",
    heroDesc: "Something extraordinary is in development. A new flavor experience that will push the boundaries of what a snack can be.",
    image: "/flavor_mystery.png",
    color: "#F5F5F7",
    story: "",
    process: "",
    ingredients: "",
    allergens: "",
    nutrition: [],
    pairings: [],
    storage: "",
    weight: "",
    origin: "",
  },
  "sel-de-l-himalaya": {
    title: "Sel de l'Himalaya",
    tagline: "Pureté Sublime, Élevée",
    heroDesc: "L'élégance intemporelle du sel rose de l'Himalaya rencontre le craquant éthéré du Makhana soufflé à la main. Un chef-d'œuvre minimaliste pour le palais exigeant.",
    image: "/flavor_salt_v2.png",
    color: "#FDF6F0",
    story: "Extrait des anciennes mines de sel de Khewra au pied de l'Himalaya, notre sel rose contient plus de 84 oligo-éléments préservés depuis 250 millions d'années. Associé à la texture délicate et aérée des meilleures graines de Makhana du Bihar, il crée un snack à la fois profondément simple et profondément satisfaisant. C'est la saveur qui a lancé notre aventure — un hommage à la philosophie selon laquelle les meilleurs ingrédients n'ont besoin que d'eux-mêmes.",
    process: "Chaque graine de Makhana est récoltée à la main dans les étangs préservés du Bihar, séchée au soleil pendant 48 heures, puis soufflée par des méthodes traditionnelles de chaleur — sans huile, sans machines. Les graines sont ensuite légèrement vaporisées d'huile d'olive extra vierge pressée à froid et saupoudrées de sel rose de l'Himalaya finement moulu. Le résultat est un snack avec moins de 2% de matières grasses qui délivre un craquant satisfaisant à chaque bouchée.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (92%), huile d'olive extra vierge pressée à froid (5%), sel rose de l'Himalaya (3%).",
    allergens: "Naturellement sans gluten. Sans noix. Sans soja. Sans produits laitiers. Fabriqué dans un établissement qui traite des noix et du sésame.",
    nutrition: [
      { label: "Énergie", value: "110 kcal" },
      { label: "Protéines", value: "3,0 g" },
      { label: "Lipides Totaux", value: "1,8 g" },
      { label: "Glucides", value: "21 g" },
      { label: "Fibres Alimentaires", value: "1,4 g" },
      { label: "Sodium", value: "180 mg" },
      { label: "Calcium", value: "25 mg" },
      { label: "Fer", value: "0,8 mg" },
    ],
    pairings: [
      "S'accorde magnifiquement avec un Chablis ou un Sauvignon Blanc frais",
      "Excellent aux côtés d'un houmous ou d'un tzatziki",
      "Un ajout raffiné à tout plateau de fromages",
      "Parfait avec de l'eau pétillante et une tranche de citron",
    ],
    storage: "Conserver dans un endroit frais et sec, à l'abri de la lumière directe du soleil. Une fois ouvert, refermer hermétiquement et consommer dans les 7 jours pour un craquant optimal.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Sel : Khewra, Pakistan · Huile d'Olive : Andalousie, Espagne",
  },
  "truffe-noire": {
    title: "Truffe Noire",
    tagline: "L'Or Noir de l'Apéro",
    heroDesc: "L'arôme envoûtant de la truffe noire du Périgord, sublimé par la légèreté nuageuse du Makhana. Le luxe accessible, redéfini.",
    image: "/flavor_truffle_v2.png",
    color: "#F5F3F0",
    story: "La truffe noire du Périgord (Tuber Melanosporum) est le joyau de la gastronomie française depuis des siècles. Prisée par les chefs du monde entier pour son arôme profond, terreux et légèrement musqué, elle transforme tout plat qu'elle touche en quelque chose d'extraordinaire. Nous avons travaillé avec des artisans truffiers de la Dordogne pour développer un assaisonnement exclusif qui capture l'essence de la truffe fraîchement râpée. Associé au craquant éthéré du Makhana soufflé à la main et à un murmure de sel de Guérande, c'est notre création la plus indulgente — la preuve que luxe et santé peuvent coexister magnifiquement.",
    process: "Notre assaisonnement à la truffe est élaboré à partir de véritables morceaux de truffe noire d'été (Tuber Aestivum) combinés à un arôme naturel de truffe dérivé de la prestigieuse variété du Périgord. Les graines de Makhana sont d'abord légèrement enrobées d'huile d'olive extra vierge, puis le mélange à la truffe est soigneusement appliqué dans notre installation à température contrôlée pour préserver les composés aromatiques volatils. Enfin, une délicate touche de sel de Guérande récolté à la main ajoute une complexité minérale.",
    ingredients: "Graines d'Euryale Ferox soufflées (Makhana) (86%), huile d'olive extra vierge (6%), morceaux de truffe noire d'été (Tuber Aestivum) (3%), arôme naturel de truffe (2%), sel de Guérande (3%).",
    allergens: "Naturellement sans gluten. Sans noix. Sans soja. Sans produits laitiers. Contient de la truffe. Fabriqué dans un établissement qui traite des noix et du sésame.",
    nutrition: [
      { label: "Énergie", value: "118 kcal" },
      { label: "Protéines", value: "3,5 g" },
      { label: "Lipides Totaux", value: "2,5 g" },
      { label: "Glucides", value: "20,5 g" },
      { label: "Fibres Alimentaires", value: "1,5 g" },
      { label: "Sodium", value: "160 mg" },
      { label: "Calcium", value: "22 mg" },
      { label: "Fer", value: "0,9 mg" },
    ],
    pairings: [
      "Exceptionnel avec un verre de Bourgogne vieilli ou de Barolo",
      "Sublime aux côtés d'un Comté affiné ou d'un Parmigiano-Reggiano",
      "Élève tout plateau de charcuterie à des sommets gastronomiques",
      "Parfait avec du champagne pour les célébrations",
    ],
    storage: "Conserver dans un endroit frais et sec, à l'abri de la lumière directe du soleil. Une fois ouvert, refermer hermétiquement et consommer dans les 5 jours pour préserver l'arôme de truffe.",
    weight: "Format : 30g",
    origin: "Makhana : Bihar, Inde · Truffe : Dordogne, France · Sel : Guérande, France",
  },
  "bientot": {
    title: "Bientôt…",
    tagline: "Le Prochain Chapitre",
    heroDesc: "Quelque chose d'extraordinaire est en cours de développement. Une nouvelle expérience gustative qui repoussera les limites de ce qu'un snack peut être.",
    image: "/flavor_mystery.png",
    color: "#F5F5F7",
    story: "",
    process: "",
    ingredients: "",
    allergens: "",
    nutrition: [],
    pairings: [],
    storage: "",
    weight: "",
    origin: "",
  },
  "raw-bulk-kernels": {
    title: "Raw Premium Bulk Kernels",
    tagline: "B2B Procurement & Import",
    heroDesc: "Jumbo 6+ Suta grade raw popped water lily pops (Makhana) for bulk commercial export, snack manufacturers, and wholesale distribution.",
    image: "/real_makhana.png",
    color: "#F5E6D3",
    story: "Directly sourced from our sustainable farms and farmer cooperatives in Bihar, India. Our raw kernels are processed with rigorous hygiene and quality controls to meet international export specifications.",
    process: "Harvested, sorted, graded, and packaged in a central, audited processing facility. Fully compliant with NABL lab tests and EU food import regulations.",
    ingredients: "100% Raw Popped Water Lily Seeds (Euryale Ferox).",
    allergens: "Naturally gluten-free. Packaged in a nut-free facility.",
    nutrition: [
      { label: "Energy", value: "350 kcal / 100g" },
      { label: "Protein", value: "9.7 g / 100g" },
      { label: "Carbohydrates", value: "77 g / 100g" },
      { label: "Dietary Fiber", value: "7.6 g / 100g" },
    ],
    pairings: [
      "Ideal for roasting, seasoning, and chocolate-coating applications",
      "Perfect for high-protein ingredient formulations",
    ],
    storage: "Store in cool, dry conditions in air-tight container. Shelf life up to 12 months.",
    weight: "Minimum Order Quantity: 1 Metric Ton",
    origin: "Bihar, India",
  },
};
